test

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,35 +1,35 @@
-version: 0.2
-phases:
-  install:
-    runtime-versions:
-      java: openjdk11
-      python: 3.7
-    commands:
-      -  pip install --upgrade 'six~=1.15.0'
-      -  pip install 'pyyaml < 6.0'
-      -  pip install --upgrade 'aws-sam-translator~=1.22.0'
-      -  pip install --upgrade 'docker~=4.0'
-      -  pip install --upgrade 'pyyaml~=5.4'
-      -  pip install pre-commit cloudformation-cli-java-plugin
-  build:
-    commands:
-      - pre-commit run --all-files
-      - |
-        if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
-          cd $CODEBUILD_SRC_DIR
-          # skip hidden folders
-          dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d)
-          echo "Folders to build: $dirs"
-          for directory in $dirs; do
-            cd "$directory"
-            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=debug -B clean verify --no-transfer-progress -X -e
-            if [ "$?" -ne 0 ] ; then
-                echo "Build failed!"
-                exit 1
-            else
-                cd ".."
-            fi
-          done
-        else
-          echo "$CODEBUILD_SRC_DIR is empty"
-        fi
+#version: 0.2
+#phases:
+#  install:
+#    runtime-versions:
+#      java: openjdk11
+#      python: 3.7
+#    commands:
+#      -  pip install --upgrade 'six~=1.15.0'
+#      -  pip install 'pyyaml < 6.0'
+#      -  pip install --upgrade 'aws-sam-translator~=1.22.0'
+#      -  pip install --upgrade 'docker~=4.0'
+#      -  pip install --upgrade 'pyyaml~=5.4'
+#      -  pip install pre-commit cloudformation-cli-java-plugin
+#  build:
+#    commands:
+#      - pre-commit run --all-files
+#      - |
+#        if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
+#          cd $CODEBUILD_SRC_DIR
+#          # skip hidden folders
+#          dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d)
+#          echo "Folders to build: $dirs"
+#          for directory in $dirs; do
+#            cd "$directory"
+#            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=debug -B clean verify --no-transfer-progress -X -e
+#            if [ "$?" -ne 0 ] ; then
+#                echo "Build failed!"
+#                exit 1
+#            else
+#                cd ".."
+#            fi
+#          done
+#        else
+#          echo "$CODEBUILD_SRC_DIR is empty"
+#        fi
